[workspace]
authors = ["gandres42 <gandres2416@gmail.com>"]
channels = ["conda-forge", "robostack-noetic"]
name = "planner_ws"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-noetic-desktop = ">=1.5.0,<2"
catkin_tools = ">=0.9.5,<0.10"
